using Content.Client.Message;
using Content.Shared._Mriya.Nuke;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Mriya.Nuke;

[GenerateTypedNameReferences]
public sealed partial class MriyaRMCNuclearChargeWindow : DefaultWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnStart;
    public event Action? OnAbort;

    private TimeSpan? _detonatesAt;

    public MriyaRMCNuclearChargeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartButton.OnPressed += _ => OnStart?.Invoke();
        AbortButton.OnPressed += _ => OnAbort?.Invoke();
    }

    public void SetState(MriyaRMCNuclearChargeBuiState state)
    {
        StatusLabel.SetMarkup(state.Status);
        StartButton.Disabled = !state.CanStart;
        AbortButton.Disabled = !state.CanAbort;
        _detonatesAt = state.DetonatesAt;
        UpdateCountdown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_detonatesAt != null)
            UpdateCountdown();
    }

    private void UpdateCountdown()
    {
        if (_detonatesAt == null)
        {
            CountdownLabel.Visible = false;
            StatusSpacer.Visible = true;
            return;
        }

        var remaining = _detonatesAt.Value - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        CountdownLabel.Visible = true;
        StatusSpacer.Visible = false;
        CountdownLabel.SetMarkup($"[color=red][font size=42][bold]{FormatCountdown(remaining)}[/bold][/font][/color]");
    }

    private static string FormatCountdown(TimeSpan remaining)
    {
        var totalMinutes = (int) Math.Floor(remaining.TotalMinutes);
        var centiseconds = remaining.Milliseconds / 10;
        return $"{totalMinutes:00}:{remaining.Seconds:00}:{centiseconds:00}";
    }
}
