using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mriya.Hunter;

[GenerateTypedNameReferences]
public sealed partial class RedHorizontalSeparator : Control
{
    public RedHorizontalSeparator()
    {
        RobustXamlLoader.Load(this);
    }
}
