- type: department
  parent: CMDepartmentBase
  id: MRweyaPMC
  name: mriya-department-weya-pmc
  description: mriya-department-weya-pmc-description
  color: "#83b5b0"
  roles:
  - CMPMCForceLeadPVE
  - CMPMCTeamLeadPVE
  - CMPMCGunnerPVE
  - CMPMCCorpsmanPVE
  - CMPMCOperatorPVE
  departmentRadio: null
  headOfDepartment: CMPMCForceLeadPVE
