using System.Numerics;
using Content.Shared._Mriya.Terminal;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Utility;
using Robust.Shared.Timing;
using System.Threading;
using System.Threading.Tasks;

namespace Content.Client._Mriya.Terminal;

[GenerateTypedNameReferences]
public sealed partial class MriyaTerminalWindow : DefaultWindow
{
    public event Action<string>? OnMessageEntered;

    private List<string> _currentMessages = new();
    private float _animationProgress = 0f;
    private bool _isAnimating = false;
    private const float CharactersPerSecond = 50f;

    public MriyaTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        
        InputBar.OnTextEntered += args => SendMessage();
        SendButton.OnPressed += _ => SendMessage();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isAnimating || _currentMessages.Count == 0)
            return;

        var lastMessage = _currentMessages[^1];
        _animationProgress += args.DeltaSeconds * CharactersPerSecond;

        if (_animationProgress >= lastMessage.Length)
        {
            _animationProgress = lastMessage.Length;
            _isAnimating = false;
        }

        UpdateDisplay(InputContainer.Visible, (int)_animationProgress);
    }

    private void SendMessage()
    {
        if (string.IsNullOrWhiteSpace(InputBar.Text))
            return;

        OnMessageEntered?.Invoke(InputBar.Text.ToUpper());
        InputBar.Text = string.Empty;
    }

    public void SetState(MriyaTerminalState state)
    {
        InputContainer.Visible = state.IsInput;

        var green = Color.FromHex("#00DD00");
        if (!string.IsNullOrEmpty(state.AuthorizedName))
        {
            AuthLabel.Visible = true;
            AuthLabel.Text = $"АВТОРИЗОВАНО ЯК {state.AuthorizedName.ToUpper()}";
            AuthLabel.FontColorOverride = green;
        }
        else
        {
            AuthLabel.Visible = false;
        }

        // Check if we have new messages to animate
        bool hasNew = state.Messages.Count > _currentMessages.Count || 
                      (state.Messages.Count > 0 && _currentMessages.Count > 0 && state.Messages[^1] != _currentMessages[^1]);

        _currentMessages = new List<string>(state.Messages);

        if (hasNew)
        {
            _animationProgress = 0f;
            _isAnimating = true;
        }
        else if (!_isAnimating)
        {
            UpdateDisplay(state.IsInput, -1);
        }
    }

    private void UpdateDisplay(bool isInput, int animationLength)
    {
        var green = Color.FromHex("#00DD00");
        var msg = new FormattedMessage();

        if (isInput)
        {
            if (_currentMessages.Count > 0)
            {
                var text = _currentMessages[^1];
                
                // Strip the [ROLE]: prefix FIRST from the full string
                if (text.StartsWith("[") && text.Contains("]: "))
                {
                    var index = text.IndexOf("]: ");
                    text = text[(index + 3)..];
                }

                // THEN apply animation length
                if (animationLength >= 0 && animationLength < text.Length)
                    text = text[..animationLength];

                msg.AddMarkupOrThrow($"[color={green.ToHex()}][font=Monospace]{FormattedMessage.EscapeText(text.ToUpper())}[/font][/color]\n");
            }
        }
        else
        {
            for (int i = 0; i < _currentMessages.Count; i++)
            {
                var text = _currentMessages[i];
                if (i == _currentMessages.Count - 1 && animationLength >= 0 && animationLength < text.Length)
                    text = text[..animationLength];

                msg.AddMarkupOrThrow($"[color={green.ToHex()}][font=Monospace]{FormattedMessage.EscapeText(text.ToUpper())}[/font][/color]\n");
            }
        }

        MessageHistory.SetMessage(msg);
        
        // Force wrap at 470px (window is 500px)
        MessageHistory.MaxWidth = 470;
        MessageHistory.InvalidateMeasure();
        
        Scroll.SetScrollValue(new Vector2(0, 1000000));
    }
}
