# TSEPA - (Three Suns Empire Policing Authority) - TSE style Police, like the CMB but for heavy TSE focused colonies. Please change when we have a new name for the sector.

- type: rank
  id: RMCRankTSEPAConstable
  name: Констебль
  prefix: Кнст.

- type: rank
  id: RMCRankTSEPASeniorConstable
  name: Старший Констебль
  prefix: Ст. Кнст.

- type: rank
  id: RMCRankTSEPASergeant
  name: Сержант
  prefix: С-нт.

- type: rank
  id: RMCRankTSEPAInspector
  name: Інспектор
  prefix: Інсп.

- type: rank
  id: RMCRankTSEPAChiefInspector
  name: Старший Інспектор
  prefix: Ст. Інсп.

- type: rank
  id: RMCRankTSEPACommander
  name: Командер
  prefix: Ком.

- type: rank
  id: RMCRankTSEPADeputyCommissioner
  name: Заступник Комісара
  prefix: Заст. Ком.

- type: rank
  id: RMCRankTSEPACommissioner
  name: Комісар
  prefix: Ком.

