using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class MriyaTerminalAdminWindow : DefaultWindow
{
    public MriyaTerminalAdminWindow()
    {
        RobustXamlLoader.Load(this);
        
        MessageInput.OnTextEntered += _ => Submit();
        SubmitButton.OnPressed += _ => Submit();
    }

    private void Submit()
    {
        if (string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        var message = MessageInput.Text;
        IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"terminalmsg \"{message.Replace("\"", "\\\"")}\"");
        Close();
    }
}
