using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Sich.Language;

namespace Content.Client._Sich.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class HunterTranslatorWindow : DefaultWindow
{
    public event Action<string>? OnSendMessage;
    public event Action<HunterTranslationCategory>? OnTargetChanged;

    public HunterTranslatorWindow()
    {
        RobustXamlLoader.Load(this);

        SendButton.OnPressed += _ => SendMessage();
        MessageLineEdit.OnTextEntered += _ => SendMessage();

        TargetOption.AddItem(Loc.GetString("hunter-translator-target-all"), (int) HunterTranslationCategory.All);
        TargetOption.AddItem(Loc.GetString("hunter-translator-target-human"), (int) HunterTranslationCategory.Human);
        TargetOption.AddItem(Loc.GetString("hunter-translator-target-xeno"), (int) HunterTranslationCategory.Xeno);

        TargetOption.OnItemSelected += args =>
        {
            TargetOption.SelectId(args.Id);
            OnTargetChanged?.Invoke((HunterTranslationCategory) args.Id);
        };
    }

    public void UpdateState(HunterTranslationCategory target)
    {
        TargetOption.SelectId((int) target);
    }

    private void SendMessage()
    {
        if (string.IsNullOrWhiteSpace(MessageLineEdit.Text))
            return;

        OnSendMessage?.Invoke(MessageLineEdit.Text);
        MessageLineEdit.Text = string.Empty;
    }

    protected override void Opened()
    {
        base.Opened();
        MessageLineEdit.GrabKeyboardFocus();
    }
}
