- type: entity
  parent: AdminObserver
  id: RMCAdminObserver
  categories: [ HideSpawnMenu ]
  components:
#  - type: PropCaller – Mriya. Зайві кнопки
  - type: Loadout
    prototypes: [ RMCMobAghostGear ]
  - type: IntrinsicUI
    uis:
    # Mriya start. Для мапінгу
      enum.RadarConsoleUiKey.Key:
        toggleAction: ActionAGhostShowRadar
    # Mriya end
  - type: Inventory
    templateId: human
  - type: RMCAdminGhost

- type: startingGear
  parent: MobAghostGear
  id: RMCMobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: RMCAdminPDA
  storage:
    back:
    - RMCAdminAccessConfigurator
    - HandheldHealthAnalyzerUnpowered
    - RMCAdminHealthAnalyzer
    - DoorRemoteAll
    - AdminHypo
    - MeleeDebug200
    - ToolDebug
    - RMCTabletCO
    - RMCWelderAdmin
    - CMMultitool
