- type: loadout
  id: MRCONightVisionVisor
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: CMJobCommandingOfficer
      time: 630000 # Платина, 175 годин
  equipment:
    belt: MRGlassesCOSight
