- type: loadout
  id: MRSEANightVisionVisor
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: CMJobSeniorEnlistedAdvisor
      time: 252000 # Золото, 70 годин
  equipment:
    eyes: MRGlassesSEASight
