- type: loadout
  id: MRSEANightVisionVisor
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: CMJobSeniorEnlistedAdvisor
      time: 252000 # Золото, 70 годин
  equipment:
    belt: MRGlassesSEASight # візор з'являється на поясі щоб можна було обрати окуляри й вони не падали на землю коли стаєш уявним другом
