- type: rank
  id: RMCRankWeYaOperator
  name: Оператор
  prefix: ОПР.
  paygrade: ПВК-ОП

- type: rank
  id: RMCRankWeYaEnforcer
  name: Виконавець
  prefix: ВИК.
  paygrade: ПВК-ВК

- type: rank
  id: RMCRankWeYaVehicleSpecialist
  name: Спеціаліст з Транспортних Засобів
  prefix: СЦТЗ.
  paygrade: ПВК-ТС

- type: rank
  id: RMCRankWeYaSupportSpecialist
  name: Спеціаліст Підтримки
  prefix: СЦП.
  paygrade: ПВК-СП

- type: rank
  id: RMCRankWeYaMedicalSpecialist
  name: Медичний Спеціаліст
  prefix: СЦМ.
  paygrade: ПВК-СМ

- type: rank
  id: RMCRankWeYaWeaponSpecialist
  name: Збройний Спеціаліст
  prefix: СЦЗ.
  paygrade: ПВК-СЗ

- type: rank
  id: RMCRankWeYaXenoSpecialist
  name: Спеціаліст з Ксено
  prefix: SPX.
  paygrade: ПВК-СКС

- type: rank
  id: RMCRankWeYaTraumaSurgeon
  name: Хірург-Травматолог
  prefix: Лік.
  paygrade: ПВК-ЛІК

- type: rank
  id: RMCRankWeYaCorporateTechnician
  name: Корпоративний Технік
  prefix: ТЕХ.
  paygrade: ПВК-ТЕХ

- type: rank
  id: RMCRankWeYaEliteResponder
  name: Елітний Відповідач
  prefix: ЕЛВ.
  paygrade: ПВК-ЕЛВ

- type: rank
  id: RMCRankWeYaEliteMedic
  name: Елітний Медик
  prefix: ЕЛМ.
  paygrade: ПВК-ЕЛМ

- type: rank
  id: RMCRankWeYaEliteGunner
  name: Елітний Стрілець
  prefix: ЕЛС.
  paygrade: ПВК-ЕЛС

- type: rank
  id: RMCRankWeYaPMCSynthetic
  name: Синтетик
  prefix: СИНТ.
  paygrade: ПВК-СИНТ

- type: rank
  id: RMCRankWeYaTeamLeader
  name: Лідер Команди
  prefix: ЛКМ.
  paygrade: ПВК-ЛК

- type: rank
  id: RMCRankWeYaFieldOperaionsLeader
  name: Лідер Польових Операцій
  prefix: ЛПО.
  paygrade: ПВК-ЛПО

- type: rank
  id: RMCRankWeYaForceLeader
  name: Лідер Сил
  prefix: ЛС.
  paygrade: ПВК-ЛС

- type: rank
  id: RMCRankWeYaEliteTeamLeader
  name: Елітний Лідер Команди
  prefix: ЕЛКМ.
  paygrade: ПВК-ЕЛК

- type: rank
  id: RMCRankWeYaSiteDirector
  name: Директор Комплексу ПВК
  prefix: Директор
  paygrade: ПВК-ДИР

- type: rank
  id: RMCRankWeYaForceCommand
  name: Командир Сил ПВК
  prefix: КОС.
  paygrade: ПВК-КОС

- type: rank
  id: RMCRankWeYaWhiteout
  name: Бойовий Юніт Команди Коректор
  prefix: КОР.
  paygrade: ???
